opt_in_rules:
  - force_unwrapping
  - force_cast
  - trailing_whitespace
  - unused_import
  - explicit_init
  - empty_count
  - file_header
  - vertical_whitespace_between_cases
  - sorted_imports
  - yoda_condition
  - closure_spacing
  - implicit_return
#  - discouraged_optional_boolean
  - multiline_arguments
  - multiline_parameters
  - vertical_whitespace_closing_braces
  - redundant_nil_coalescing
  - unused_declaration
  - weak_delegate

line_length: 135
type_body_length: 320
function_body_length: 80
